import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import '@fontsource/open-sans';
import "./Styles/globals.css";


const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400","500", "600", "700"],
  variable: "--font-open-sans", 
});
export const metadata: Metadata = {
  title: "YouLyst",
  description: "Generated by YouLyst",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={openSans.variable}>
      <body
        className={`${openSans.variable} ${openSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
